name: CICD
on: push
jobs:
  cicd:
    runs-on: [self-hosted, linux]
    permissions:
       contents: read
       packages: write
       id-token: write
    steps:
      # https://github.com/internetarchive/cicd
      - uses: internetarchive/cicd@v1
        with:
          BASE_DOMAIN: 'netlobo.com'
          NOMAD_ADDR: 'http://bigl.netlobo.com:4646'
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
